db:
  container_name: db
  image: mysql:5.7
  ports:
    - '3306:3306'
  environment:
    - MYSQL_DATABASE=InvSync
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
  volumes:
  #  - './DATA/:/var/lib/mysql/'
    - '/etc/timezone:/etc/timezone:ro'
  tty: true
  restart: always

phpmyadmin:
  container_name: phpmyadmin
  image: phpmyadmin/phpmyadmin
  ports:
    - '8080:80'
  environment:
    - PMA_HOST=db
    - PMA_USER=username
    - PMA_PASSWORD=password
  volumes:
    - '/etc/timezone:/etc/timezone:ro'
  links:
    - db
  tty: true
  restart: always
